import type { Metadata } from 'next';
import { getLocale } from 'next-intl/server';

import { manrope, roboto } from '@/shared/fonts';
import { Toaster } from '@/shared/ui/toaster';

import { RootProviders } from './providers/RootProviders';
import './styles/global.css';

export const metadata: Metadata = {
	title: 'Funding Stax',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();

	return (
		<html lang={locale}>
			<body
				className={`${manrope.variable} ${roboto.variable} overflow-hidden`}
			>
				<RootProviders>{children}</RootProviders>
				<Toaster />
			</body>
		</html>
	);
}
