import '../styles/globals.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Manrope, Roboto } from 'next/font/google';

import { Header, Sidebar } from '@/components';
import { Flex } from '@/components/ui';

import styles from './layout.module.scss';

const manrope = Manrope({
	weight: ['400', '500', '600', '700'],
	variable: '--font-manrope',
	subsets: ['latin'],
});
const roboto = Roboto({
	weight: ['500', '700'],
	variable: '--font-roboto',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Funding Stax',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={`${manrope.variable} ${roboto.variable}`}>
				<NextIntlClientProvider messages={messages}>
					<Header />
					<Flex align='start' gap='16'>
						<Sidebar />
						<main className={styles.mainWrapper}>{children}</main>
					</Flex>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
