import '../styles/globals.css';
import type { Metadata } from 'next';
import { Manrope, Roboto } from 'next/font/google';

import { Header, Sidebar } from '@/components';

const manrope = Manrope({
	weight: ['400', '500', '600', '700'],
	variable: '--font-manrope',
	subsets: ['latin'],
});
const roboto = Roboto({
	weight: ['500', '700'],
	variable: '--font-roboto',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Funding Stax',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${manrope.variable} ${roboto.variable}`}>
				<Header />
				<main>
					<Sidebar />
					{children}
				</main>
			</body>
		</html>
	);
}
