export { PlatformPage } from './PlatformPage/PlatformPage';
export { ChallengeHistoryPage } from './ChalllengeHistoryPage/ChalllengeHistoryPage';
// export { AuthPage } from './AuthPage/AuthPage';
export { ChallengeDetails } from './ChallengeDetails/ChallengeDetails';
export { ReferralsPage } from './Affiliates/ReferralsPage';
export { ReferralsListPage } from './Affiliates/ReferralsListPage';
export { ReferralsLoading } from './Affiliates/ReferralsLoading';
export { ReferralPayoutsPage } from './Payouts/ReferralPayoutsPage';
export { ChallengePayoutsPage } from './Payouts/ChallengePayoutsPage';
export { ProfilePage } from './Profile/ProfilePage';
export { FaqPage } from './FaqPage/FaqPage';
export { BuyChallengePage } from './BuyChallengePage/BuyChallengePage';
