export { PlatformPage } from './PlatformPage/PlatformPage';
export { ChallengeHistoryPage } from './ChalllengeHistoryPage/ChalllengeHistoryPage';
export { AuthPage } from './AuthPage/AuthPage';
export { ChallengeDetails } from './ChallengeDetails/ChallengeDetails';
export { NewThemePage } from './NewThemePage/NewThemePage';
export { UserInfoPage } from './Profile/UserInfoPage';
export { BillingPage } from './Profile/BillingPage';
export { ReferralsPage } from './Affiliates/ReferralsPage';
export { ReferralsListPage } from './Affiliates/ReferralsListPage';
